###订单服务端口号
server:
  port: 9202
###服务别名---服务注册到注册中心的名称
spring:
  application:
    name: blog-center
eureka:
  client:
    service-url:
      ###当前订单服务注册到eureka服务地址
      defaultZone: http://127.0.0.1:8101/eureka
    ###是否需要注册到eureka上
    register-with-eureka: true
    ###需要检索服务
    fetch-registry: true

feign:
  hystrix:
    enabled: true



