###商品秒杀前台页面
server:
  port: 88
###服务别名---服务注册到注册中心的名称
spring:
  application:
    name: goodsService
  jackson:
    #      日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

#  设置日志级别：debug，便于查看全局异常
logging:
  level:
   com.code: debug